spring:
  application:
    name: offer-verdict
server:
  port: 8080
  thymeleaf:
    cache: false

app:
  publicBaseUrl: http://localhost:8080
  baselineLivingCost: 1800
  sitemapChunkSize: 5000
  devReloadEnabled: true

seo:
  salary-bucket:
    interval: 10000
    min: 30000
    max: 500000

logging:
  level:
    root: INFO
